background_path: /home/mdn/bor/EiT-ROS/src/pose_estimation/src/backgroundBrown.png
input_topic_rgb: /camera/rgb/image_raw
input_topic_depth: /camera/depth/image_raw
output_topic: /pose_est

threshold_binary: 10
erosion_size: 2
dilation_size: 4
mask_x: 235
mask_y: 220
mask_w: 285
mask_h: 145